### ISSUE TITLE
Allow the user to do there own parsing

### ISSUE THREAD

**Issue by SNavleen** [mslosarek/node-rets#4] opened 2020-05-10 03:07 UTC
Hi, I just came across your npm module, its very well done and I think it might be better to let the user parse there own data, since the default parsing method is if the data is returned in COMPACT mode. If something is returned in Standard-XML mode, then the parsing fails. The best example would be for Agent or Office search results. I would like to use this further. Please let me know what you think as soon as possible since I am in the process of building a REST API with it.

**Comment by mslosarek** [comment] 2020-05-13 00:05
Hi, Thanks for the feedback. I can definitely add a custom parser, I think that would make a good addition. One thing you may not know, is that the search call, does support different standard XML (though not currently documented). The last argument is the format:
```
const searchProperties = await client.search(
  resourceType,
  classType,
  query,
  { limit: 1, offset: 1 },
  'STANDARD-XML' 
);
```
Do you have a sample response that isn't parsing correctly, I have access to a limited number of RETS servers?

Thanks,

Mark

**Comment by SNavleen** [comment] 2020-05-13 12:02
Hey, I did notice that the last argument was for format. What happens is since the search query in standard-xml returns information in a different format (aka without columns filed on how the data is split) this line of becomes invalid https://github.com/mslosarek/node-rets/blob/master/lib/client.js#L156 (since the function depends on that).

So what ends up happening is the return statement looks like `                                                                       { TotalCount: 1, Count: 0, Objects: [] } `

Here is a sample request to a search query with standard-xml
![Capture](https://user-images.githubusercontent.com/8814404/81809883-0b3f9680-94f0-11ea-8cd3-a58a7ed5bbd5.PNG)

**Comment by mslosarek** [comment] 2020-05-13 18:43
Can you send me this XML (or something similar) and I'll make sure it can be processed.

**Comment by SNavleen** [comment] 2020-05-17 22:00
Sorry for the delay, here is the data for some object. Keep in mind everything can have certain values and keys (and certain ones can be missing). Best thing would be to do is json parse the xml or just return the body so the user can parse it as they like.

`<RETS ReplyCode="0" ReplyText="Operation Successful">
<METADATA>
<METADATA-LOOKUP_TYPE Resource="Property" Lookup="FireplaceFuel" Date="Fri, 29 Jun 2012 00:00:00 GMT" Version="1.00.00001">
<LookupType>
<MetadataEntryID>1</MetadataEntryID>
<Value>1</Value>
<LongValue>Wood</LongValue>
<ShortValue>Wood</ShortValue>
</LookupType>
<LookupType>
<MetadataEntryID>2</MetadataEntryID>
<Value>2</Value>
<LongValue>Gas</LongValue>
<ShortValue>Gas</ShortValue>
</LookupType>
<LookupType>
<MetadataEntryID>3</MetadataEntryID>
<Value>3</Value>
<LongValue>Electric</LongValue>
<ShortValue>Electric</ShortValue>
</LookupType>
<LookupType>
<MetadataEntryID>4</MetadataEntryID>
<Value>4</Value>
<LongValue>Mixed</LongValue>
<ShortValue>Mixed</ShortValue>
</LookupType>
<LookupType>
<MetadataEntryID>5</MetadataEntryID>
<Value>5</Value>
<LongValue>Pellet</LongValue>
<ShortValue>Pellet</ShortValue>
</LookupType>
<LookupType>
<MetadataEntryID>6</MetadataEntryID>
<Value>6</Value>
<LongValue>Propane</LongValue>
<ShortValue>Propane</ShortValue>
</LookupType>
<LookupType>
<MetadataEntryID>7</MetadataEntryID>
<Value>7</Value>
<LongValue>Unknown</LongValue>
<ShortValue>Unknown</ShortValue>
</LookupType>
<LookupType>
<MetadataEntryID>8</MetadataEntryID>
<Value>8</Value>
<LongValue>Oil</LongValue>
<ShortValue>Oil</ShortValue>
</LookupType>
</METADATA-LOOKUP_TYPE>
</METADATA>
</RETS>`

**Comment by mslosarek** [comment] 2020-05-20 02:03
@SNavleen I found the issue, the CREA XML is a different format than I had previously seen. I have added a few fixes to handle this type of issue. Please check [version 0.2.6](https://www.npmjs.com/package/node-rets/v/0.2.6) to see if your issue is resolved.

**Comment by mslosarek** [comment] 2020-05-21 20:18
Closing since I think the issue is resolved.

**Closed by mslosarek** 2020-05-21 20:18 UTC
Labels: enhancement

**Comment by SNavleen** [comment] 2020-05-23 14:16
Thank you for the update, I haven't had a chance to take a look at it, but when I do I will let you know. I did look at the issue that was merged, and the code does look like it fixes what I was looking for. Thank you so much for the help :)
